docs/_includes/homepage-content.html
docs/assets/external-homepage/external-homepage-prod.css
docs/assets/external-homepage/external-homepage-prod.less

Splitting list items into two row containers fixes the issue.

ID-187 Fix popover row overflow bug on Safari

---

docs/assets/external-homepage/external-homepage-prod.css
docs/assets/external-homepage/external-homepage-prod.less

Use `display: {table, table-cell}` instead of flexbox to lay out links in the popover.
Now works correctly on iOS 9. Interesting juxtaposition between brand-new operating system and ancient layout technique.

ID-187 Fix popover

---

docs/assets/external-homepage/homepage-carousel.jquery.js

Clicking the Warwick logo smooth-scrolls to the first item on the page, instead of reloading the page.

SBTWO-7341 Link Warwick logo to first menu item on external HP

---

js/account-popover.jquery.js
less/notifications.less
less/utility-bar.less
less/variables.less

Things learnt:
* When we call `.popover(opts)` on an element, `.data("bs.popover")` becomes available immediately. We can call `.tip()` on this to manipulate the classes on the popover element. This is a lot more reliable than modifying the template retroactively, or trying to destrory and recreate the popover.
* MWE: https://codepen.io/anon/pen/qjXNGZ?editors=1111
This should also fix the "append 0 when can't connect to MyWarwick" issue.

ID-228 Fall back to the usual WebSignOn popover on smaller screens

---

docs/_includes/components/utility-bar.html
docs/_includes/utility-bar.html
docs/_layouts/external-homepage-prod.html
js/account-popover.jquery.js

It appears jQuery's data function converts DOM attributes to e.g.
booleans if they match true/false. The original test assumed the value
would always be a string, and used the strict === comparison operator.
Since this assumption was wrong, it made it impossible to actually enable
the MW feature after PR #45 was merged.
~~TODO: Remove diff of generated files which seem to be in the repo.~~

Fix up the feature flag to be more lenient and enable it by default

---

js/account-popover.jquery.js
js/navigation.jquery.js
js/reflow-event.jquery.js

Open to suggestion on whether this is the right fix to make, or whether we should do something to defer the call of `this.reflow();` on `reflow-event.jquery.js:70` to give time for the listeners to be bound.

ID-246 Handle reflow event being listened for after it's already been fired

---

README.md

Previously the shim situation wasn't properly documented, although an update was intended to be made before 1.6.0 was released.
This PR adds a note to explain that the shims are not included by default to provide v4 FA compat. It also adds a "breaking changes" entry for v1.6.0 of ID7.

Update docs for FA5

---

README.md

It took me a while to work this out so I could get `grunt serve` to work as it usually does. I think Ubuntu updated the Ruby version in the repos recently

Make a note of required Ruby version until fixed

---

docs/_includes/config-options.html
docs/assets/js/config-options.js
docs/components.html

This removes the strapline position dropdown as discussed. Additionally, it appeared that a number of components were present in the components page right-hand menu but not actually in the body of the document. I've removed all of these.

ID-264 Remove obsolete options and components

---

less/navigation.less

As discussed.
I'm unsure what the ramifications of me removing the media query actually _are_ but I've tested e.g. dropdown buttons and they still seem to work.
I've checked this on Android and w/ Firefox - it seems to work

ID-194 Attempt fix nested dropdowns

---

less/mixins.less
less/mixins/utility-bar-bg.less
less/utility-bar.less

E.g. Warwick conferences site could use this, and get the appropriate contrast on the links and notifications badge for free.
Default:
White:

Add @id7-utility-bar-bg for overriding utility bar background colour

---

docs/_includes/header.html
templates/base.html

I've tested this by:
* Visiting `https://fonts.googleapis.com`.
* Running `document.cookie="MyCookie=123"`.
* Verifying that, without the `crossorigin` attribute, the cookie is sent along with the request to fetch the font CSS.
* Verifying that, with the attribute, the cookie is *not* sent.
I've also taken the chance to drop use of protocol relative URLs for the external font. They might've made sense a while back, but we should just prefer to always fetch securely now IMO (especially since `fonts.googleapis.com` isn't HSTS preload'd).

ID-253 Set crossorigin attribute, drop protocol relative URL

---

docs/examples/hyphens/index.html
less/text-styles.less

Didn't mix in fa-icon() directly as it included some styles that we would have to override, so keeping the output slim by only including what we need.
Also fix the HTML on the example page to how it's intended to be used - it wasn't showing anything before.

ID-296 Include more of the standard fa rules.

---

less/accessibility.less
less/id7-no-fa.less
less/variables.less

This PR adds a gov.uk style orange `:focus` outline for accessibility. This currently applies to all elements, which may or may not be desirable (we could restrict to just `a`).
Screenshots:
------------
**Normal link**
**Navbar**
**Other fields**
Video showing different colour navbars is on Slack.

ID-291 Orange outlines for :focus'd elements

---

_config.yml
package.json

Release Notes - Brand - Version 2.3.9
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-288'>ID-288</a>] -         Mobile popover rules activating for some desktops
</li>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-318'>ID-318</a>] -         Sign out not visible in some Chromes v74+
</li>
</ul>
<h2>        Improvement
</h2>
<ul>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-316'>ID-316</a>] -         &quot;Skip to navigation&quot; link
</li>
</ul>

Bump version to 2.3.9 for release

---

js/navigation.jquery.js

Recursively looks for the next visible navigation bar to focus on if the user keeps pressing <kbd>→</kbd> at the end of the navbar (or <kbd>←</kbd> at the start)
[Video](https://lol768.github.io/lol768/2019-06-25%2015-02-09.mp4)

ID-317 Wrap to next/previous navbar with cursor keys

---

_config.yml
package.json

Release Notes - Brand - Version 2.4.2
<h2>        Improvement
</h2>
<ul>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-324'>ID-324</a>] -         handle horizontal scroll on non-safari browsers on mac
</li>
</ul>

Bump to version v2.4.2 for release

---

README.md
js/wide-tables.jquery.js

previously had ID7 triggers event `non-safari-mac-post-init.id7:table-responsive` seems to be an incorrect approach, as it's most likely have that event is triggered before implementer's listener is registered.
changes to have ID7 listens to the event and execute the callback, and let implementer triggers the event.

TAB-7285 post fix 

---

less/masthead.less
less/variables.less

In Firefox, outlines take into account child elements.
This PR fixes the size of the outline in Firefox, where it was previously too big. Right click -> open image should still work in Chrome.
Before:

Tweak outline sizes

---

less/accessibility.less

Lamentable use of the important in the styles - judged it to be simpler than to add a set of overrides for all the things with more important backgrounds and borders.

ID-357 Use GDS inspired focus indicator.

---

less/accessibility.less
less/masthead.less

Reinstates the outline alongside the background and black underline.

ID-372 ID-373 Make focus outline and logo visible.

---

js/account-popover.jquery.js

This is the ultimate cause of our woes with COOP, because the pop-up would otherwise inherit the sandbox flags applied to the iframe - even though it's top-level and not a navigation inside the iframe.
Due to the requirement to have a "clean slate" for COOP sites (as part of the process isolation design goal), the position adopted by browser vendors was that it was undesirable to have the sandbox flags persist in the new context that has come about due to COOP and so the navigation is blocked instead.
This PR is the long term fix alongside the T&T short term fix that I opened a [PR](https://repo.elab.warwick.ac.uk/projects/TAT/repos/app/pull-requests/124/overview) for. I believe that once _this_ ID7 PR is merged/deployed widely enough (probably Sitebuilder will do), we can revert today's …

Allow sandboxed iframe to create unsandboxed popups

---

js/id7-popover.js

This PR fixes an issue where if ID7 popovers were initialised on a page (for example in Tabula, Postroom etc), click-to-dismiss would fail to work for the MyWarwick account popover.
This was tested using the ID7 reference site and does not affect any behaviour of other ID7 popovers.
(thanks Adam for helping!)

ID-399 Fix MyWarwick popover click-to-dismiss with ID7 popovers initialised

---

less/masthead.less

Target for what was affixed in a masthead was changed at some point, so `affix` is now applied to the whole masthead instead of the title. However, the title is smaller than the container, and we have some large containers that weren't included. Width of sticky header should now be correct when scrolling instead of jumping around.

ID-402 Fix sticky header changing size when scrolling on wide pages

---

docs/assets/site/docs-site.less
docs/components/colour-palette/index.html
less/variables.less

This changes the colour of an existing variable, @id7-brand-green, which had been removed a few years ago presumably because it was a horrible colour. It's back now and it is dark

ID-408 Reintroduce Warwick Green.

---

less/floating-labels.less

Have no transformation on Search Warwick input label so it will not overflow and cause the cookie banner to scroll in two dimensions.
Link to related JIRA: https://bugs.elab.warwick.ac.uk/browse/SBTWO-10013.

SBTWO-10013 Have no transformation on Search Warwick input label so it will not overflow and cause cookie banner to scroll in two dimensions.

---

README.md
docs/assets/site/docs-site.less
docs/components/colour-palette/index.html
less/variables.less

Docs page updated for the colours we currently show (replacing green with teal), and a link to the full brand palette page on Sitebuilder.
The primary purple colour has been changed so that's likely to be the main change noticeable when updating ID7. Otherwise only if you had referenced any of the other brand colours.
May need to wait for ID-426 to push these out as the new colours may not pair with the most contrasting text colour using the existing contrast algorithm.

ID-414 Update brand colours.

---

docs/_data/brand_palette.yml
docs/assets/css/config-options.less
docs/components/colour-palette/index.html
docs/examples/brand-testcard/index.html

To let people know we are working on this.
Also got a bit fed up with the repetitive HTML - seems like somebody didn't know about Liquid templates. Now the brand palette is generated from some YAML data, as is a brand testcard that prints out headings, links and box styles in a range of brand colours.
Adjusted config-options.less so that these brands can be applied at any level in the document, not just to the body. Allows for having multiple themes in one page.

ID-426 Add a little notice to the top.

---

less/mixins/wcag.less

Switch from lighten to tint as this always gets it a % of the way to white, rather than lighten which could send an already-light colour almost all the way to white and look ridiculous.

ID-426 Always lighten secondary nav with black.

---

README.md
docs/_includes/templates/base.html
docs/_includes/utility-masthead.html
docs/_layouts/borderless.html
docs/_layouts/default.html
docs/_layouts/empty.html
docs/_layouts/home.html
docs/_layouts/hp-2019.html
docs/_layouts/many-menus.html
docs/_layouts/wide.html
less/footer.less
less/header.less
less/masthead.less
less/mixins/branding.less
less/utility-bar.less
templates/base.html

W cutout in footer removed in ID7.1.
Reworked it so you add it to the <body> element. Should make it easier to apply to various apps if it's all in one place.

ID-428 ID7.1 removes W cutout in footer, now applied to <body> elements

---

docs/assets/css/config-options.less
docs/assets/site/docs-site.less
docs/assets/site/site.less
less/default-theme.less
less/design-tokens/all.less
less/design-tokens/colors.less
less/mixins/branding.less
less/tokens.less
less/variables.less

In addition to .apply-brand you also now need to apply the new mixin at the relevant level, usually inside a `:root`.

ID-424 CSS properties for many colours.

---

docs/assets/css/config-options.less
less/design-tokens/colors.less
less/main-content/box-styles.less
less/mixins/box-styles.less
less/mixins/branding.less
less/variables.less
vitest/brand-colours.ts
vitest/less-functions.ts

These shouldn't have any visual effect on existing content, but will define a set of CSS properties and classes to activate them.
Page elements can be designed using the nonspecific "primary" color tints and contrasting values - then by adding one of the id7-brand-COLOUR classes to any containing element, they will become tints of that colour.
Also a helper class called `.bg-primary-500` (and again for all the other tints) which just sets the background and color to that tint+contrast. Something you could fairly easily implement yourself but helpful to have a basic implementation around, though it currently doesn't play well with headings and links and things that set a brand colour.

ID-446 Define new colour palette.

---

docs/_includes/getting-started/download.html
less/masthead.less

Swap half the padding for margin. Still looks good, it's accessible, everyone's happy.
Also fix a link in the getting started guide.

ID-462 Utility bar links too close to wordmark.
