UniversityofWarwick/id7

docs/_includes/components/footer.html
docs/_includes/components/navigation.html
docs/_includes/components/site-title.html
docs/_includes/components/utility-bar.html
docs/_includes/nav/bacon-ipsum-child-secondary.html
docs/_includes/nav/bacon-ipsum-secondary.html
docs/_includes/nav/components-secondary.html
docs/_includes/nav/examples-secondary.html
docs/_includes/nav/main.html
docs/components.html

Nav now works like Sitebuilder. I've corrected the relevant docs, and filled out some more of the missing components with some words. I daresay they could be better but I figure better to have something to start from than nothing.

ID-54 Reconcile id7 nav with current Sitebuilder. Fix up some docs.

---

dist/images/logo-divider-blue.svg
dist/images/logo-divider-gold.svg
dist/images/logo-divider-gray.svg
dist/images/logo-divider-green.svg
dist/images/logo-divider-orange.svg
dist/images/logo-divider-purple.svg
dist/images/logo-divider-red.svg
dist/templates/base.html
docs/_includes/components/footer.html
docs/_includes/divider.html
docs/_includes/footer.html
docs/_includes/templates/base.html
docs/_layouts/default.html
docs/_layouts/home.html
images/logo-divider-blue.svg
images/logo-divider-gold.svg
images/logo-divider-gray.svg
images/logo-divider-green.svg
images/logo-divider-orange.svg
images/logo-divider-purple.svg
images/logo-divider-red.svg
images/src/logo-divider.svg
templates/base.html

Probably merits browserstackery.

ID-190 Tweak horizontal divider

---

js/navigation.jquery.js

Add extra headroom config to fire an event whenever the navigation is hidden or shown. Allows us to respond in apps that use ID7.

TAB-5263 - Fire events when headroom shows/hides the navigation

---

js/account-popover.jquery.js

Add feature flag for the new MyWarwick work. Trigger needs a `data-` attribute in order for the MyWarwick functionaliy to be activated.

Feature flag support

---

less/notifications.less

Fix overzealous font rule to prevent tofu

---

js/account-popover.jquery.js
less/bootstrap-fixes.less

* Disables MW functionality on iPads
* Fixes caret display more widely on iPads, as discussed

ID-234 ID-233 iPad related work

---

docs/assets/external-homepage/homepage-carousel.jquery.js
docs/assets/external-homepage/jquery.panelSnap.js

Currently live on the homepage and working as expected

SBTWO-8057 Update panelSnap.js and fix problems with homepage carousel

---

Gruntfile.js
README.md
bower.json
dist/js/vendor/jquery.doubleScroll-0.6.js
js/tests/index.html

https://github.com/avianey/jqDoubleScroll/pull/11

ID-257 Bump version of doubleScroll for inline style fix

---

js/navigation.jquery.js

Giving future Jeff precious hours of his life back

Prevent the page from jumping to the content anchor when changing tabs

---

docs/_includes/header.html

I don't _think_ we need the subsite styles, this seems to work.

ID-252 Add site styles to fix BG selection on testcard

---

js/safari-user-agent-detect.modernizr.js
less/mixins/svg-background-with-fallback.less

Screenshots and reasoning in the JIRA.

ID-250: Switch to vector (SVG) backgrounds for desktop Safari

---

less/mixins/link-styles.less

ID-258 Apply link colours to .btn-link, too

---

README.md
_config.yml
package.json

Release Notes - Brand - Version 2.1.0
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-244'>ID-244</a>] -         Notification count not visible on light utility bar
</li>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-270'>ID-270</a>] -         Nav breadcrumbs mispositioned
</li>
</ul>
<h2>        Improvement
</h2>
<ul>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-210'>ID-210</a>] -         Improve print view on A3 landscape
</li>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-219'>ID-219</a>] -         Allow search suggest component to be reinitialised
</li>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-221'>ID-221</a>] -         Clear floated images in box styles
</li>
<li>[<a …

Release v2.1.0

---

dist/templates/base.html
templates/base.html

In the releases I've downloaded, the name is "theme" - not "style"

Update example template

---

js/safari-user-agent-detect.modernizr.js

Revert ID-250, Safari SVG rendering is still problematic

---

.travis.yml

Simple travis config that runs tests and tries to build docs.

ID-275 Try and add Travis support for id7 builds/tests

---

_config.yml
package.json

Hopefully final hotfix version today..

Version bump for release version 2.3.6

---

Gemfile.lock
package.json

Check it out over at https://id7.netlify.com
Interestingly enough it's also fixed **ID-279 Version string is empty in the docs**

Updates for netlify

---

docs/components/carousel/index.html

We included some images from an insecure origin. This PR fixes that, which should appease Netlify's PR status checks.

ID-320 Remove mixed content

---

dist/templates/base.html
docs/_includes/components/search.html
docs/_includes/masthead.html
docs/_layouts/external-homepage-prod.html
docs/_layouts/hp-2019.html
templates/base.html

Fixes ID-321 Search form contains no submit button
TODO:

Mark submit button in search

---

docs/_includes/utility-bar.html
docs/_layouts/external-homepage-prod.html
docs/_layouts/hp-2019.html

Since SBTWO-8780, text only mode has been RIP

---

_config.yml
package.json

Bump to new minor version per suggestion.
----------
<h1>Release Notes - Brand - Version 2.4.0</h1>
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-319'>ID-319</a>] -         Focus outline of header text is clipped
</li>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-321'>ID-321</a>] -         Search form contains no submit button
</li>
</ul>
<h2>        Task
</h2>
<ul>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-322'>ID-322</a>] -         Update jQuery to version 3.4.1
</li>
</ul>
<h2>        Improvement
</h2>
<ul>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-266'>ID-266</a>] -         When inputting to the search text field move the label up above the field
</li>
<li>[<a …

Version to v2.4.0 for release

---

_config.yml
package.json

Bump to version 2.4.3 in preparation for release

---

_config.yml
package.json

<h2>        Bug
</h2>
<ul>
<li>[<a href='https://bugs.elab.warwick.ac.uk/browse/ID-326'>ID-326</a>] -         Do not style screen-reader spans inside pagination elements
</li>
</ul>

Bump version for release

---

_config.yml
package-lock.json
package.json

Bug
[ID-327] - IE11 shouldn't fail the flexbox feature test
Improvement
[ID-328] - Don't wait for DOMReady to add feature detection classes to prevent FOUC
[ID-329] - Update dependencies

Release v2.4.5

---

.github/workflows/nodejs.yml

Add Node CI tests via GH Actions

---

RELEASES.md

This should hopefully make life a bit easier.

Document automatic release upload behaviour

---

README.md

Mostly to see if Travis will block the merge.. but also, yay HTTPS :lock:

Extra security

---

docs/examples/bootstrap-testcard/index.html
js/id7-bundle.js
js/id7-popover.js
less/bootstrap-fixes.less
less/mixins/link-styles.less

- ID-341 Steal Tabula popovers and put them in ID7

ID-341: Robust click-away popovers

---

_config.yml
package.json

Release hightlight:
- [ID-341] Robust popovers with click to dismiss behaviour

Bump to v2.5.5 for release

---

docs/_includes/nav/examples-secondary.html
docs/_includes/nav/main.html
docs/_includes/nav/menus.html
docs/_layouts/many-menus.html
docs/assets/js/reflow-events.js
docs/examples/index.html
docs/examples/reflow/index.html
js/reflow-event.jquery.js
js/screen-sizes.js

[ID-343] Refactor id7:reflow to (partially) be replaced with MediaQueryList listener 

---

RELEASES.md

Remove obsolete information

---

js/hp-2019/more-links-popover.jquery.js

Fix focus order after opening more links popover

---

docs/_includes/components/navigation.html
docs/_includes/components/next-previous-links.html
docs/_includes/components/utility-bar.html
docs/_includes/components/warwick-site-links.html
docs/_includes/masthead.html
docs/_includes/nav/bacon-ipsum-child-secondary.html
docs/_includes/nav/bacon-ipsum-secondary.html
docs/_includes/nav/components-secondary.html
docs/_includes/nav/examples-secondary.html
docs/_includes/nav/main.html
docs/_includes/nav/menus.html
docs/_includes/templates/base.html
docs/_includes/utility-bar.html
docs/_layouts/hp-2019.html
docs/_layouts/many-menus.html
templates/base.html

I've sorted it out such that we're setting the right example here, and the template provided includes aria-labels in the right places, but I guess there will need to be separate work on any template implementations we already have...

ID-362 Added aria-labels to <nav> elements

---

less/masthead.less

Tested on major browsers and IE11.

ID-388 Turned dreadful font awesome triangle into amazing CSS triangle

---

js/hp-2019/more-links-popover.jquery.js

ID-389-fix-fix Put back the line I shouldn't have removed

---

package-lock.json
package.json

ID-391 Updated typeahead to 4.1.0

---

docs/_includes/config-options.html
docs/assets/site/docs-site.less
docs/components/colour-palette/index.html
less/variables.less

ID-363 Reworked the brand colour pallet according to the new accessible rules

---

less/accessibility.less

Background and outline is more than enough for these, I think.

Suppress box-shadow based thick border on buttons

---

docs/_includes/utility-masthead.html
less/header.less
less/masthead.less
less/mixins/branding.less
less/utility-bar.less

Amazing stuff. Made it a toggle thing so that people can update their ID7 dependencies without it automatically applying and breaking any app-specific template stuff.

ID-416 ID7.1 can be toggled via class id7-point-1 to id7-utility-masthead

---

bootstrap/js/carousel.js
docs/components/carousel/index.html

Avoids the link falling back to evaluating the href if there's an error in the middle of the click handler.
Not really a concern for us but hopefully this will placate the automated scanners.
Also included, a random spray of const and let

ID-454 preventDefault first.

---

less/variables.less

ID-452 - Fix standard input height

---

docs/_includes/nav/examples-secondary.html
docs/_includes/nav/main.html
docs/_includes/nav/menus.html
docs/_layouts/many-menus.html
docs/examples/index.html
docs/examples/short/index.html
less/fixed-width-container.less

ID-467 Flex always.
